server:
  port: 8075

logging:
  level:
    com.example.msa: debug
    org.springframework.jdbc: debug

spring:
  application:
    name: msa-coffee-member
  profiles:
    include: chaos-monkey


  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    sql-script-encoding: UTF-8

  h2:
    console:
      enabled: true

mybatis:
  type-aliases-package: com.example.msa.repository
  mapper-locations: classpath:sql/*.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8071/eureka/

management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

chaos:
  monkey:
    enabled: false
    watcher:
      repository: true
    #      rest-controller: true
    assaults:
      level: 3
      latency-active: true
      latency-range-start: 3000
      latency-range-end: 6000
#    assaults:
#      watched-custom-services: com.example.msa.repository.OrderRepository, com.example.msa.rest.OrderRestController