DROP TABLE IF EXISTS COFFEE_ORDER;

CREATE TABLE COFFEE_ORDER (
    id NUMBER AUTO_INCREMENT NOT NULL,
    order_no NUMBER NOT NULL UNIQUE,
    COFFEE_NAME VARCHAR NOT NULL,
    COFFEE_COUNT NUMBER NOT NULL,
    MEMBER_NAME VARCHAR NOT NULL,
    PRIMARY KEY (ID)
);