DROP TABLE IF EXISTS ORDER;

CREATE TABLE ORDER (
    'ID' NUMBER NOT NULL,
    'ORDER_NO' NUMBER AUTO_INCREMENT NOT NULL,
    'COFFEE_NAME' VARCHAR NOT NULL,
    'COFFEE_COUNT' NUMBER NOT NULL,
    'MEMBER_NAME' VARCHAR NOT NULL,
    PRIMARY KEY ('ORDER_NO')
);